### ISSUE TITLE
bug: after pcmanfm-qt crashes, some keyboard shortcuts stop working and menubar is visible again

### ISSUE THREAD

**Issue by excalibur1234** [lxde/pcmanfm-qt#326]
i have observed this behavior often:

whenever i cut and paste huge files/folders and change something in pcmanfm-qt at the same time (e.g. folder and file names, double click on folders, cut and paste somewhere else at the same time), pcmanfm-qt crashes as soon as cut and paste has finished its job. (maybe this is a separate bug?)

after every crash, pcmanfm-qt resovers again. but now, my menubar is visible again (i always hide it) and some keyboard shortcuts stop working (CTRL+C, CTRL+V, CTRL+M, CTRL+H, DEL), while other keyboard shortcuts continue working (F2, F3, BACKSPACE).

**Comment by tsujan** [comment]
Oh, the most important part of your report is the crash itself. Could you tell how to reproduce it? Does it always happen with a hidden menubar? And do you have the latest git version?

**Comment by excalibur1234** [comment]
i think i compiled the latest git version yesterday or the day before yesterday.
but i can crash pcmanfm relatively easy for a while now (even before the menubar hidden feature was introduced).
i just tested it again: i did not hide my menu bar and i copied a large file and a large folder from one location of my hard drive to another. i did that by opening 2 windows in pcmanfm-qt and copying the files in the first and pasting the files in the second window.
after the copy process has been started, i start to change file names (of other files, not the files being copied) and change directory (just navigate my file structure) in both windows. then, i cancel the copy process and pcmanfm-qt crashes. usually it crashes when the copy process is finished, but canceling works, too.
here is my journald log: http://pastebin.com/5dgMnnzv

if i would guess what is happening i would say: whenever the pcmanfm-qt window shows a different directory at the start of a copy (or cut) process and the end of it, then pcmanfm-qt crashes.

**Comment by tsujan** [comment]
Can anyone else reproduce this crash?

@excalibur1234 
I tested with a 5-GiB file to have enough time. I renamed other files in the source and destination folders, changed to directories other than the source and destination ones, closed one or both windows, reopened them, and yet no crash happened.

I'll try to find the cause from your journald log but that won't be easy without having a way of reproducing the crash.

**Comment by excalibur1234** [comment]
i have just tested it again: 
pcmanfm-qt crashes, when i copy a large file (in one window of pcmanfm-qt). when the copy process finishes (either regularly or by canceling it) and the pcmanfm-qt window is in a different state than it was during the start of the copy process, pcmanfm-qt crashes.
my desktop background even becomes bright for a second.
all copy and paste commands were issues with mouse and right click.

**Comment by excalibur1234** [comment]
sorry, but somehow i cannot reproduce the crash anymore.
i do not know why.
as soon as i encounter it the next time (probably after a couple of reboots), i will report back.

**Comment by tsujan** [comment]
> sorry, but somehow i cannot reproduce the crash anymore.

Did you change or update anything related to PCManFM or LXQT?

**Comment by nonamethanks** [comment]
I think I have the same bug. The steps to reproduce it for me are:

1) Open two different folders in two tabs
2) Copy/move a large folder from one to another
3) Close one of the tabs and change the other to another directory unrelated to the previous two involved in the moving/copying

This causes pcmanfm-qt to crash once the copying/moving process is finished or interrupted, every single time.
gdb:
```
Thread 1 "pcmanfm-qt" received signal SIGSEGV, Segmentation fault.
0x00007ffff7bac6b0 in fm_file_info_get_path () from /usr/lib/libfm.so.4
Error detected on fd 0
error detected on stdin

```

**Comment by tsujan** [comment]
@nonamethanks
For the crash to happen, should a folder be copied, in contrast to a file? And do you mean large in size (~ how many MiB?) or in the number of contents (~ how many files?)

As I told above, I couldn't reproduce the crash. @excalibur1234 also told that he couldn't anymore.

(1) @excalibur1234 and @nonamethanks: which distros do you have? What are the versions of gvfs and glib?
(2) @nonamethanks: how did you install LXQT?

**Comment by nonamethanks** [comment]
I'm running Arch Linux with gvfs 1.26.3-1 and glib2 2.46.2-4. 

The folder i'm using to reproduce this bug has ~400 files and is ~20 GB. 
I just tried with a large file (5.4 GB) and the result is the same - exact same output from gdb.

Also I'm not running lxqt, just openbox.

**Comment by tsujan** [comment]
@nonamethanks
Thanks! I'll test on Manjaro too. Yet another question: Were both source and destination on the hard drive or on a mounted external hard, usb flash, etc.?

**Comment by nonamethanks** [comment]
The folder I reproduced the bug with was local and its destination was on an external HDD, while the single file had both source and destination on the same external HDD.

I just tried copying the same local folder to another destination on the same internal HDD and reproduced the bug again, so it doesn't seem like the bug depends on that.

**Comment by excalibur1234** [comment]
i am running manjaro (net install) with lxqt and openbox and gvfs 1.26.3-1 and glib2 2.46.2-4. 

i just tested nonamethanks' method for crashing pcmanfm-qt-git with a large file in 2 local folders containing only a few folders and files. it did not crash.

i will test it in the next couple of days and report back, when pcmanfm-qt crashes again.

**Comment by tsujan** [comment]
Yes, I did the same in Manjaro, with a 2-GiB folder containing 1900 files (`/var/cache/apt/archives` from another partition, where Debian resided) and no crash. Maybe a downstream problem that came into Manjaro from Arch and then was fixed.

**Comment by tsujan** [comment]
@npmiller It seems to me that the destructor of FileOperation suffers from the same issue you fixed in https://github.com/lxde/libfm-qt/pull/20/commits/8dcf29a1c28102d2fb1a3688558f861048196ddb. What do you think?

**Comment by npmiller** [comment]
Maybe, although in the FileOperation destructor, the jobs are disconnected from the callbacks, so it's not as bad, but maybe they should be cancelled as well.

Given the description there may also be some piece of data that gets used by several FileOperation objects when it really shouldn't, so the second operations would temper with the one running in the background, and obviously that would only really show up with long running jobs.

Although I haven't tried replicating it yet so this is pure speculation.

**Comment by tsujan** [comment]
@npmiller Thanks! Let's think about it for a while! Unfortunately, this issue can't be reproduced easily.

**Comment by excalibur1234** [comment]
since i created this issue, i have switched from openbox to kwin and from proprietary nvidia driver to free mouveau driver. i have also built all git components of lxqt multiple times now.

i do not have a problem anymore with pcmanfm-qt crashing. it is quite stable.

i still have problems with keyboard shortcuts: some keyboard shortcuts work (e.g. CTRL + M, ALT + F2, CTRL + A, F2), some only do not work in pcmanfm-qt but work in firefox (e.g. CTRL + C, CTRL + V, DEL).

strangely, i also have problems with keyboard shortcuts in notepadqq (CTRL + F is not working, but CTRL + SHIFT + F and CTRL + H are working).

i am using qt5.6 and i have heard that it breaks keyboard shortcuts. could this be the source of this issue?

**Comment by excalibur1234** [comment]
pcmanfm-qt is mostly stable for me for a while now.

also, i have found a workaround for the keyboard shortcut problem as described here: https://github.com/lxde/pcmanfm-qt/issues/401#issuecomment-265843965

all bug fixes can be discussed in issue #401 as well. closing this issue.
